# Generated by Django 5.2.12 on 2026-04-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fullname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='type_of_delivery',
            field=models.CharField(choices=[('NP', 'Нова пошта'), ('SF', 'Самовивіз')], default='NP', max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='type_of_payment',
            field=models.CharField(choices=[('IP', 'Оплата на місці')], default='IP', max_length=2),
        ),
    ]
