# Generated by Django 5.2.12 on 2026-04-10 16:15

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_order_fullname_alter_order_type_of_delivery_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type_of_delivery',
            field=models.CharField(choices=[('NP', 'Нова пошта'), ('UP', 'Укр пошта')], default='NP', max_length=2),
        ),
    ]
